### ISSUE TITLE
Electron implementation of python QT stack

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-desktop#232]
## Description
The old pythonQT stack is outdated and few of the app features broke while python 3 migration. I propose that we start working on new implementation and ditch the old stack. We would make use of the battle-tested electron framework for developing native desktop apps. I have also proposed an architecture design that will help us make use of the python **PSL** library and also do so without blocking the *main* or *UI* threads. @fragm3 and I plan to finish this over the period of GSOC.

![Untitled Diagram](https://user-images.githubusercontent.com/19551058/56195616-efe72b00-6052-11e9-8f29-64d5e45e1a35.jpg)

## Goals
- [ ] Reimplement the whole Python QT app using Electron.
- [ ] Redesign UI, come up with a unified theme. 
- [ ] Migrate all the features available on android app.
- [ ] Rigorous testing of the newly build up under heavy data load.

**Comment by fragm3** [comment]
@AakashMallik sounds like a plan. Let's get started!

**Comment by fragm3** [comment]
**Before the GSOC period starts(till end of community bonding period):**

- We plan to create the whole structuring of the dashboard. We plan to use either antd or Material UI for styling our components.
- Create modular and reusable styled-components which can be used across the application
- Create layouts which will help reduce code redundancy and make it easier to manage more number of instruments and components.
- Create oscilloscope component and get feedback from our mentor @CloudyPadmal @mariobehling. Make improvement and use this generalised layout for other instruments.
- Create and implement general dashboard components like help, guide, settings
- We plan to explore electron js more, and make sure the code written is efficient.

**Overall plan:**

Basic Dashboard → Connection to device, electron → Implement Oscilloscope component → Implement other Instruments components →Export Data,  Data visualisation →  User, device settings →  Refactor Code → Documentation

Dev Approach : Implementation, add features → Fix issues, bugs → Finalise the project → Maintenance
